emperorList = [("First Century", [(("Augustus", "IMPERATOR CAESAR DIVI FILIVS AVGVSTVS"), ((-27, "BC"), (14, "AD")), ((-63, "BC"), (14, "AD")), "He died of natural causes."),
                                    (("Tiberius", "TIBERIVS CAESAR DIVI AVGVSTI FILIVS AVGVSTVS" ), ((14, "AD"), (37, "AD")), ((-42, "BC"), (37, "AD")), "He probably died natural causes, but quite possibly assassinated by Caligula,\n\t  or praetorian prefect Naevius Sutorius Macro."),
                                    (("Caligula", "GAIVS IVLIVS CAESAR AVGVSTVS GERMANICVS" ), ((37, "AD"), (41, "AD")), ((12, "AD"), (41, "AD")), "Assassinated in a conspiracy involving senators and Praetorian Guards."),
                                    (("Claudius", "TIBERIVS CLAVDIVS CAESAR AVGVSTVS GERMANICVS" ), ((41, "AD"), (54, "AD")), ((-10, "BC"), (54, "AD")), "Was probably poisoned by his wife Agrippina the Younger, in favour of her son\n\t  Nero, possibly natural causes."),
                                    (("Nero", "NERO CLAVDIVS CAESAR AVGVSTVS GERMANICVS" ), ((54, "AD"), (68, "AD")), ((37, "AD"), (68, "AD")), "He committed suicide after being declared a public enemy by the Senate."),
                                    (("Galba", "SERVIVS SVLPICIVS GALBA CAESAR AVGVSTVS" ), ((68, "AD"), (69, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Otho", "MARCVS SALVIVS OTHO CAESAR AVGVSTVS" ), ((69, "AD"), (69, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Vitellius", "AVLVS VITELLIVS GERMANICVS AVGVSTVS" ), ((69, "AD"), (69, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Vespasian", "TITVS FLAVIVS CAESAR VESPASIANVS AVGVSTVS" ), ((69, "AD"), (79, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Titus", "TITVS FLAVIVS CAESAR VESPASIANVS AVGVSTVS" ), ((79, "AD"), (81, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Domitian", "TITVS FLAVIVS CAESAR DOMITIANVS AVGVSTVS" ), ((81, "AD"), (96, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Nerva", "MARCVS COCCEIVS NERVA CAESAR AVGVSTVS" ), ((96, "AD"), (98, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Trajan", "CAESAR MARCVS VLPIVS NERVA TRAIANVS AVGVSTVS" ), ((98, "AD"), (117, "AD")), ((1, "AD"), (1, "AD")), "")]),

               ("Second Century", [(("Trajan", "CAESAR MARCVS VLPIVS NERVA TRAIANVS AVGVSTVS" ), ((98, "AD"), (117, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Hadrian", "CAESAR PVBLIVS AELIVS TRAIANVS HADRIANVS AVGVSTVS" ), ((117, "AD"), (138, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Antoninus Pius", "CAESAR TITVS AELIVS HADRIANVS ANTONINVS AVGVSTVS PIVS" ), ((138, "AD"), (161, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Marcus Aurelius", "CAESAR LVCIVS AVRELIVS VERVS AVGVSTVS" ), ((161, "AD"), (180, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Lucius Verus", "CAESAR MARCVS AVRELIVS ANTONINVS AVGVSTVS" ), ((161, "AD"), (169, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Commodus", "CAESAR MARCVS AVRELIVS COMMODVS ANTONINVS AVGVSTVS" ), ((177, "AD"), (192, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Pertinax", "CAESAR PVBLIVS HELVIVS PERTINAX AVGVSTVS" ), ((193, "AD"), (193, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Didius Julianus", "CAESAR MARCVS DIDIVS SEVERVS IVLIANVS AVGVSTVS" ), ((193, "AD"), (193, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Septimius Severus", "CAESAR LVCIVS SEPTIMIVS SEVERVS PERTINAX AVGVSTVS" ), ((193, "AD"), (211, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Caracalla", "CAESAR MARCVS AVRELIVS SEVERVS ANTONINVS PIVS AVGVSTVS" ), ((198, "AD"), (217, "AD")), ((1, "AD"), (1, "AD")), "")]),

                ("Third Century", [(("Septimius Severus", "CAESAR LVCIVS SEPTIMIVS SEVERVS PERTINAX AVGVSTVS" ), ((193, "AD"), (211, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Caracalla", "CAESAR MARCVS AVRELIVS SEVERVS ANTONINVS PIVS AVGVSTVS" ), ((198, "AD"), (217, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Geta", "CAESAR PVBLIVS SEPTIMIVS GETA AVGVSTUS" ), ((209, "AD"), (211, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Macrinus", "CAESAR MARCVS OPELLIVS SEVERVS MACRINVS AVGVSTVS PIVS FELIX" ), ((217, "AD"), (218, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Elgabalus", "MARCVS AVRELIVS ANTONINVS AVGVSTVS" ), ((218, "AD"), (222, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Severus Alexander", "CAESAR MARCVS AVRELIVS SEVERVS ALEXANDER AVGVSTVS" ), ((222, "AD"), (235, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Maximinus I", "CAESAR GAIVS IVLIVS VERVS MAXIMINVS AVGVSTVS" ), ((235, "AD"), (238, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Gordian I", "CAESAR MARCVS ANTONIVS GORDIANVS SEMPRONIANVS AFRICANVS AVGVSTVS" ), ((238, "AD"), (238, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Gordian II", "CAESAR MARCVS ANTONIVS GORDIANVS SEMPRONIANVS ROMANVS AFRICANVS AVGVSTVS" ), ((238, "AD"), (238, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Pupienus", "CAESAR MARCVS CLODIVS PVPIENVS MAXIMVS AVGVSTVS" ), ((238, "AD"), (238, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Balbinus", "CAESAR DECIMVS CAELIVS CALVINVS BALBINVS PIVS AVGVSTVS" ), ((238, "AD"), (238, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Gordian III", "CAESAR MARCVS ANTONIVS GORDIANVS AVGVSTVS" ), ((238, "AD"), (244, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Philip I", "CAESAR MARCVS IVLIVS PHILIPPVS AVGVSTVS" ), ((244, "AD"), (249, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Trajan Decius", "CAESAR GAIVS MESSIVS QVINTVS TRAIANVS DECIVS AVGVSTVS" ), ((249, "AD"), (251, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Hostilian", "CAESAR CAIVS VALENS HOSTILIANVS MESSIVS QVINTVS AVGVSTVS" ), ((251, "AD"), (251, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Trebonianus Gallus", "CAESAR GAIVS VIBIVS TREBONIANVS GALLVS AVGVSTVS" ), ((251, "AD"), (253, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Aemilian", "CAESAR MARCVS AEMILIVS AEMILIANVS AVGVSTVS" ), ((253, "AD"), (253, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Valerian", "CAESAR PVBLIVS LICINIVS VALERIANVS AVGVSTVS" ), ((253, "AD"), (260, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Gallienus", "CAESAR PVBLIVS LICINIVS EGNATIVS GALLIENVS AVGVSTVS" ), ((253, "AD"), (268, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Claudius Gothicus", "CAESAR MARCVS AVRELIVS CLAVDIVS AVGVSTVS" ), ((268, "AD"), (270, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Quintillus", "CAESAR MARCVS AVRELIVS CLAVDIVS QVINTILLVS AVGVSTVS" ), ((270, "AD"), (270, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Aurelian", "CAESAR LVCIVS DOMITIVS AVRELIANVS AVGVSTVS" ), ((270, "AD"), (275, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Tacitus", "CAESAR MARCVS CLAVDIVS TACITVS AVGVSTVS" ), ((275, "AD"), (276, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Florian", "CAESAR MARCVS ANNIVS FLORIANVS AVGVSTVS" ), ((276, "AD"), (276, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Probus", "CAESAR MARCVS AVRELIVS PROBVS AVGVSTVS" ), ((276, "AD"), (282, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Carus", "CAESAR MARCVS AVRELIVS CARVS AVGVSTVS" ), ((282, "AD"), (283, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Numerian", "CAESAR MARCVS AVRELIVS NVMERIVS NVMERIANVS AVGVSTVS" ), ((283, "AD"), (284, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Carinus", "CAESAR MARCVS AVRELIVS CARINVS AVGVSTVS" ), ((283, "AD"), (285, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Diocletian", "CAESAR GAIVS AVRELIVS VALERIVS DIOCLETIANVS AVGVSTVS" ), ((284, "AD"), (305, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Maximian", "CAESAR MARCVS AVRELIVS VALERIVS MAXIMIANVS AVGVSTVS" ), ((286, "AD"), (305, "AD")), ((1, "AD"), (1, "AD")), "")]),

               ("Fourth Century", [(("Diocletian", "CAESAR GAIVS AVRELIVS VALERIVS DIOCLETIANVS AVGVSTVS" ), ((284, "AD"), (305, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Maximian", "CAESAR MARCVS AVRELIVS VALERIVS MAXIMIANVS AVGVSTVS" ), ((286, "AD"), (305, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Galerius", "CAESAR GAIVS GALERIVS VALERIVS MAXIMIANVS AVGVSTVS" ), ((305, "AD"), (311, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Constantius I", "CAESAR MARCVS FLAVIVS VALERIVS CONSTANTIVS AVGVSTVS" ), ((305, "AD"), (306, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Severus II", "FLAVIVS VALERIVS SEVERVS AVGVSTVS" ), ((306, "AD"), (307, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Constantine the Great", "CAESAR FLAVIVS VALERIVS AVRELIVS CONSTANTINVS AVGVSTVS" ), ((306, "AD"), (337, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Maxentius", "MARCVS AVRELIVS VALERIVS MAXENTIVS AVGVSTVS" ), ((306, "AD"), (312, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Licinius I", "CAESAR GAIVS VALERIVS LICINIVS AVGVSTVS" ), ((308, "AD"), (324, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Maximinus II", "CAESAR GALERIVS VALERIVS MAXIMINVS AVGVSTVS" ), ((311, "AD"), (313, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Constantine II", "CAESAR FLAVIVS CLAVDIVS CONSTANTINVS AVGVSTVS" ), ((337, "AD"), (340, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Constantius II", "CAESAR FLAVIVS IVLIVS CONSTANTIVS AVGVSTVS" ), ((337, "AD"), (361, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Constans", "CAESAR FLAVIVS IVLIVS CONSTANS AVGVSTVS" ), ((337, "AD"), (350, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Vetranio", "CAESAR FLAVIVS VETRANIO AVGVSTVS" ), ((350, "AD"), (350, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Julian", "CAESAR FLAVIVS CLAVDIVS IVLIANVS AVGVSTVS" ), ((360, "AD"), (363, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Jovian", "CAESAR FLAVIVS IOVIANVS AVGVSTVS" ), ((363, "AD"), (364, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Valentinian I", "FLAVIVS VALENTINIANVS AVGVSTVS" ), ((364, "AD"), (375, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Valens", "FLAVIVS IVLIVS VALENS AVGVSTVS" ), ((364, "AD"), (378, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Gratian", "FLAVIVS GRATIANVS AVGVSTVS" ), ((367, "AD"), (383, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Valentinian II", "FLAVIVS VALENTINIANVS INVICTVS AVGVSTVS" ), ((375, "AD"), (392, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Theodosius I", "FLAVIVS THEODOSIVS AVGVSTVS" ), ((379, "AD"), (395, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Magnus Maximus", "FLAVIVS MAGNVS MAXIMVS AVGVSTVS" ), ((383, "AD"), (388, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Honorius", "FLAVIVS HONORIVS AVGVSTVS" ), ((393, "AD"), (423, "AD")), ((1, "AD"), (1, "AD")), "")]),

                 ("Fifth Century", [(("Honorius", "FLAVIVS HONORIVS AVGVSTVS" ), ((393, "AD"), (423, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Constantine III", "FLAVIVS CLAVDIVS CONSTANTINVS AVGVSTVS" ), ((407, "AD"), (411, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Constantius III", "FLAVIVS CONSTANTIVS AVGVSTVS" ), ((421, "AD"), (421, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Joannes", "IOHANNES AVGVSTVS" ), ((423, "AD"), (425, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Valentinian III", "FLAVIVS PLACIDIVS VALENTINIANVS AVGVSTVS" ), ((424, "AD"), (455, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Petronius Maximus", "FLAVIVS ANICIVS PETRONIVS MAXIMVS AVGVSTVS" ), ((455, "AD"), (455, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Avitus", "EPARCHIVS AVITVS AVGVSTVS" ), ((455, "AD"), (456, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Majorian", "FLAVIVS IVLIVS VALERIVS MAIORIANVS AVGVSTVS" ), ((457, "AD"), (461, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Libius Severus", "FLAVIVS LIBIVS SEVERVS SERPENTIVS AVGVSTVS" ), ((461, "AD"), (465, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Anthemius", "PROCOPIVS ANTHEMIVS AVGVSTVS" ), ((467, "AD"), (472, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Olybrius", "FLAVIVS ANICIVS OLYBRIVS AVGVSTVS" ), ((472, "AD"), (472, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Glycerius", "FLAVIVS GLYCERIVS AVGVSTVS" ), ((473, "AD"), (474, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Julius Nepos", "FLAVIVS IVLIVS NEPOS AVGVSTVS" ), ((474, "AD"), (480, "AD")), ((1, "AD"), (1, "AD")), ""),
                                    (("Romulus Augustulus", "ROMVLVS AVGVSTVS" ), ((475, "AD"), (476, "AD")), ((460, "AD"), (495, "AD")), "Regarded as emperor more from historical convention than accuracy, his rule\n\t  never extended beyond portions of the Italian peninsula and was not recognized\n\t  by Eastern Emperor Zeno. Deposed by Odoacer, who then ruled in the name\n\t  of Julius Nepos until the latter's death in 480, which formally ended\n\t  the separate western empire; most likely lived out his life\n\t  on a private villain obscurity.")])]
function output_reign()
      for century in emperorList
            l = length(century[2])
            @printf("In the %s, there were %d emperors over %d years.\n", century[1], l, century[2][end][2][2][1]-century[2][1][2][1][1])
            for emperor in century[2]
                  reign = (emperor[2][2][1] - emperor[2][1][1])
                  @printf("\tEmperor %s, or %s, who ruled from %d %s to %d %s, %s%s year%s.\n", emperor[1][1], emperor[1][2], (emperor[2][1][1]>0?emperor[2][1][1]:-emperor[2][1][1]), emperor[2][1][2], emperor[2][2][1], emperor[2][2][2], (reign>3 ? "" : (reign!=0?"only " : "")), (reign==0 ? "less then 1" : string(reign)), (reign<=1 ? "" : "s"))
                  @printf("\t  He was born in %d %s, and died in %d %s at the age of %d.\n\t  %s\n", (emperor[3][1][1]>0?emperor[3][1][1]:-emperor[3][1][1]), emperor[3][1][2], emperor[3][2][1], emperor[3][2][2], emperor[3][2][1] - emperor[3][1][1], emperor[4])
            end
            println()
      end
end

output_reign()
